-- Referrals ledger for doctor incentives. Run in Supabase SQL editor if migrations are not applied automatically.
-- doctor_id references profiles(user_id) — the referring doctor's auth user id.

create table if not exists public.referrals (
  id integer generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  doctor_id uuid null,
  facility_id uuid null,
  referral_amount smallint not null,
  referral_date date not null default (current_date),
  is_settled boolean not null default false,
  settlement_date date null,
  constraint referrals_pkey primary key (id),
  constraint referrals_doctor_id_fkey foreign key (doctor_id) references profiles (user_id) on delete set null,
  constraint referrals_facility_id_fkey foreign key (facility_id) references facilities (id) on delete set null
);

create index if not exists referrals_doctor_id_idx on public.referrals (doctor_id);
create index if not exists referrals_referral_date_idx on public.referrals (referral_date desc);

alter table public.referrals enable row level security;

-- Doctors can read only their own referral rows (matches auth.uid() to profiles.user_id).
drop policy if exists "referrals_select_own_as_doctor" on public.referrals;
create policy "referrals_select_own_as_doctor"
  on public.referrals
  for select
  to authenticated
  using (doctor_id = auth.uid());

-- Optional: service role / admin inserts — adjust for your backend; app may be read-only for doctors.
-- create policy "referrals_insert_admin" on public.referrals for insert to authenticated with check (false);
